name: 创建私有仓库

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_ACTOR: ${{ github.actor }}
    
    steps:
      #- uses: actions/checkout@v3
      - name: 运行命令
        run: |
          echo $GITHUB_TOKEN
          echo $GITHUB_ACTOR
          curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GITHUB_TOKEN"\
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/orgs/$GITHUB_ACTOR/repos \
              -d '{"name":"Hello-World","description":"This is your first repository","private":true}' \
          | echo
