name: 复制公共仓库为私有仓库

on:
  workflow_dispatch:
    inputs:
      target:
        description: '复制的公共仓库名称 (例：wgp-2020/actions_copyrepo)'
        required: true
        type: string
      ref:
        description: '公共仓库的分支/标签 （例：master）'
        required: true
        type: string
      name:
        description: '创建的私有仓库名称 (例：actions_copyrepo)'
        required: true
        type: string
      

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.TOKEN }}
      ACTOR: ${{ github.actor }}
      TARGET: ${{ inputs.target }}
      REF: ${{ inputs.ref }}
      NAME: ${{ inputs.name }}
    
    steps:
      - name: 创建私有仓库
        run: |
          response=$(curl -Lsw "%{http_code}" -X POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \
                          -H "Authorization: Bearer $TOKEN" \
                          https://api.github.com/user/repos \
                          -d '{"name":"'${NAME}'","description":"源自'${TARGET}':'${REF}'","private":true}')
          code=$(echo "$response" | tail -1)
          if [[ "$code" != "201" ]]; then 
            echo "$response"
            exit 1 
          fi
      
      - name: 复制公共仓库
        run: |
          git clone -b ${REF} https://github.com/${TARGET}.git
          cd "$(echo "${TARGET}" | cut -d'/' -f2)"
          git remote set-url origin https://${TOKEN}@github.com/${ACTOR}/${NAME}.git
          git push
