name: 测试

on:
  workflow_dispatch:
    inputs:
      target:
        description: '复制的公共仓库名称'
        required: true
        type: string
      ref:
        description: '公共仓库的分支/标签'
        required: true
        type: string
      name:
        description: '创建的私有仓库名称'
        required: true
        type: string
      

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
      GITHUB_ACTOR: ${{ github.actor }}
      TARGET: ${{ inputs.target }}
      REF: ${{ inputs.ref }}
      NAME: ${{ inputs.name }}
    
    steps:
      - uses: actions/checkout@v3
      - name: 签出公共仓库
        uses: actions/checkout@v3
        with:
          repository: ${{ env.TARGET }}
          ref: ${{ env.REF }}
          path: repo
          
      - name: 提交公共仓库
        run: |
          chmod +x *
          cd repo
          ../copy.sh
